{
 "title": "Sql Server",
 "description": "Performance and health metrics for Prometheus MSSQL Exporter running on docker.",
 "tags": [
  "prometheus",
  "SQL Server"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "up" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "up{job=\"$job\"}"
   },
   {
    "name": "database_name",
    "query": "mssql_connections{instance=\"$instance\"}"
   }
  ]
 },
 "panels": [
  { "title": "Databases properties", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DATABASES HEALTH",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "State OFFLINE",
     "query": "SELECT mean(\"total\") FROM \"State OFFLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "singlestat",
   "description": "Number of lock requests per second that resulted in a deadlock since last restart",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mssql_deadlocks{instance=\"$instance\"}",
     "measurement": "State ONLINE",
     "query": "SELECT \"total\" FROM \"State ONLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Kill Connection Errors",
   "type": "singlestat",
   "description": "Number of kill connection errors/sec since last restart",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mssql_kill_connection_errors{instance=\"$instance\"}",
     "measurement": "State OFFLINE",
     "query": "SELECT \"total\" FROM \"State OFFLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Total Wait Time",
   "type": "singlestat",
   "description": "Wait time (s) of stall since last restart",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mssql_io_stall_total_seconds{instance=\"$instance\", db=\"$database_name\"} / 1000",
     "measurement": "State SUSPECT",
     "query": "SELECT \"total\" FROM \"State SUSPECT\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Number of Transact-SQL",
   "type": "singlestat",
   "description": "Number of Transact-SQL command batches received per second. This statistic is affected by all constraints (such as I/O, number of users, cachesize, complexity of requests, and so on). High batch requests mean good throughput",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mssql_batch_requests{instance=\"$instance\"}",
     "measurement": "State RECOVERING",
     "query": "SELECT \"total\" FROM \"State RECOVERING\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Number of page faults",
   "type": "singlestat",
   "description": "Number of page faults since last restart",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mssql_page_fault_count{instance=\"$instance\"}",
     "legendFormat": "Page Fault Count",
     "measurement": "State RECOVERY_PENDING",
     "query": "SELECT \"total\" FROM \"State RECOVERY_PENDING\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Virtual memory",
   "type": "singlestat",
   "description": "Total physical memory",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mssql_virtual_memory_bytes{instance=\"$instance\"} / 1024 / 1024  ",
     "measurement": "Performance metrics",
     "query": "SELECT \"Point In Time Recovery\" FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter",
     "select": [
      [
       { "params": [ "Point In Time Recovery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
     ]
    }
   ]
  },
  {
   "title": "Resident memory",
   "type": "singlestat",
   "description": "Total physical memory",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mssql_resident_memory_bytes{instance=\"$instance\"} / 1024 / 1024  ",
     "measurement": "Performance metrics",
     "query": "SELECT \"Point In Time Recovery\" FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter",
     "select": [
      [
       { "params": [ "Point In Time Recovery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
     ]
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "description": "Available physical memory",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mssql_os_memory{instance=\"$instance\", state=\"available\"} / 1024 / 1024",
     "measurement": "Recovery Model FULL",
     "query": "SELECT \"total\" FROM \"Recovery Model FULL\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Total Page File",
   "type": "graph",
   "description": "Total page file in KB",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mssql_os_page_file{instance=\"$instance\",state=\"used\"} / 1024 / 1024",
     "measurement": "Recovery Model BULK_LOGGED",
     "query": "SELECT \"total\" FROM \"Recovery Model BULK_LOGGED\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Available Page File",
   "type": "singlestat",
   "description": "Available page file",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mssql_os_page_file{instance=\"$instance\",state=\"used\"} / 1024 / 1024",
     "measurement": "Recovery Model SIMPLE",
     "query": "SELECT \"total\" FROM \"Recovery Model SIMPLE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Active Connections",
   "type": "graph",
   "description": "Number of active connections",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mssql_connections{instance=\"$instance\",db=\"$database_name\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Active Connections",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "User Errors",
   "type": "graph",
   "description": "Number of user errors/sec since last restart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mssql_user_errors{instance=\"$instance\"}",
     "legendFormat": "User errors"
    }
   ]
  },
  {
   "title": "Write Stall Time (ms)",
   "type": "graph",
   "description": "Wait time (ms) of stall since last restart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms", "label": "Stall time" }
   ],
   "targets": [
    {
     "expr": "mssql_io_stall_seconds{instance=\"$instance\", db=\"$database_name\",operation=\"write\"}/1000",
     "legendFormat": "Write Stall Time"
    }
   ]
  },
  {
   "title": "Read Stall Time (ms)",
   "type": "graph",
   "description": "Wait time (ms) of stall since last restart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ms", "label": "Stall time" }
   ],
   "targets": [
    {
     "expr": "mssql_io_stall_seconds{instance=\"$instance\", db=\"$database_name\",operation=\"read\"}",
     "legendFormat": "Read Stall Time"
    }
   ]
  }
 ]
}