USE master
go
CREATE DATABASE BONITA_BPM 
ON PRIMARY
(
    NAME='BONITA_BPM',
    FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL13.SCG\MSSQL\DATA\BONITA_BPM.mdf',
    SIZE=9728KB,
    MAXSIZE=UNLIMITED,
    FILEGROWTH=65536KB
)
LOG ON
(
    NAME='BONITA_BPM_log',
    FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL13.SCG\MSSQL\DATA\BONITA_BPM_log.ldf',
    SIZE=8192KB,
    MAXSIZE=UNLIMITED,
    FILEGROWTH=65536KB
)
go
EXEC sp_dbcmptlevel 'BONITA_BPM',130
go
USE BONITA_BPM
go
EXEC sp_changedbowner 'bonitadev'
go
USE master
go
ALTER DATABASE BONITA_BPM SET ANSI_NULL_DEFAULT OFF
go
ALTER DATABASE BONITA_BPM SET ANSI_NULLS OFF
go
ALTER DATABASE BONITA_BPM SET ANSI_PADDING OFF
go
ALTER DATABASE BONITA_BPM SET ANSI_WARNINGS OFF
go
ALTER DATABASE BONITA_BPM SET ARITHABORT OFF
go
ALTER DATABASE BONITA_BPM SET AUTO_CREATE_STATISTICS ON
go
ALTER DATABASE BONITA_BPM SET AUTO_UPDATE_STATISTICS ON
go
ALTER DATABASE BONITA_BPM SET AUTO_CLOSE OFF
go
ALTER DATABASE BONITA_BPM SET AUTO_SHRINK OFF
go
ALTER DATABASE BONITA_BPM SET CONCAT_NULL_YIELDS_NULL OFF
go
ALTER DATABASE BONITA_BPM SET CURSOR_CLOSE_ON_COMMIT OFF
go
EXEC sp_replicationdboption 'BONITA_BPM','merge publish',false
go
ALTER DATABASE BONITA_BPM SET NUMERIC_ROUNDABORT OFF
go
EXEC sp_replicationdboption 'BONITA_BPM','publish',false
go
ALTER DATABASE BONITA_BPM SET QUOTED_IDENTIFIER OFF
go
ALTER DATABASE BONITA_BPM SET RECURSIVE_TRIGGERS OFF
go
EXEC sp_replicationdboption 'BONITA_BPM','subscribe',false
go
ALTER DATABASE BONITA_BPM SET TORN_PAGE_DETECTION OFF
go
ALTER DATABASE BONITA_BPM SET DATE_CORRELATION_OPTIMIZATION OFF
go
ALTER DATABASE BONITA_BPM SET ALLOW_SNAPSHOT_ISOLATION ON
go
ALTER DATABASE BONITA_BPM SET READ_COMMITTED_SNAPSHOT ON
go
ALTER DATABASE BONITA_BPM SET PARAMETERIZATION SIMPLE
go
ALTER DATABASE BONITA_BPM SET PAGE_VERIFY CHECKSUM
go
ALTER DATABASE BONITA_BPM SET RECOVERY FULL
go
ALTER DATABASE BONITA_BPM SET CURSOR_DEFAULT GLOBAL
go
ALTER DATABASE BONITA_BPM SET READ_WRITE
go
ALTER DATABASE BONITA_BPM SET MULTI_USER
go
IF DB_ID('BONITA_BPM') IS NOT NULL
    PRINT '<<< CREATED DATABASE BONITA_BPM >>>'
ELSE
    PRINT '<<< FAILED CREATING DATABASE BONITA_BPM >>>'
go
